name: Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies and build
        run: |
          npm install
          npm run build
      - name: Add SSH key to ssh-agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
         ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Git setup
        run: |
          git config --global user.email "jorgen.n.sveberg@gmail.com"
          git config --global user.name "YurgenGrimwood"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.DEPLOY_KEY }}
