name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        
      - name: Add SSH key to ssh-agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_TOKEN }}

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "jorgen.n.sveberg@gmail.com"
          git config --global user.name "yurgengrimwood"
          npm run deploy
